/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 3a57e55dd9785b974931e3bbfb9aa702)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	NEXT_PUBLIC_CONVEX_URL: "https://spotted-starling-965.convex.cloud";
	OPENROUTER_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_CONVEX_URL" | "OPENROUTER_API_KEY">> {}
}
